import { MigrationInterface, QueryRunner } from "typeorm";

export class AddProviderProfileFeatures1765953245960 implements MigrationInterface {
    name = 'AddProviderProfileFeatures1765953245960'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "client_profiles" DROP CONSTRAINT "client_profiles_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "addresses" DROP CONSTRAINT "addresses_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "provider_locations" DROP CONSTRAINT "provider_locations_address_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "provider_locations" DROP CONSTRAINT "provider_locations_provider_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "provider_languages" DROP CONSTRAINT "provider_languages_provider_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "provider_availability" DROP CONSTRAINT "provider_availability_provider_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "provider_time_off" DROP CONSTRAINT "provider_time_off_provider_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "services" DROP CONSTRAINT "services_category_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "services" DROP CONSTRAINT "services_provider_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "appointment_services" DROP CONSTRAINT "appointment_services_service_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "appointment_services" DROP CONSTRAINT "appointment_services_appointment_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "portfolio_images" DROP CONSTRAINT "FK_portfolio_images_style_category"`);
        await queryRunner.query(`ALTER TABLE "portfolio_images" DROP CONSTRAINT "portfolio_images_style_category_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "portfolio_images" DROP CONSTRAINT "portfolio_images_provider_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP CONSTRAINT "fk_appointments_portfolio_image"`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP CONSTRAINT "appointments_provider_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP CONSTRAINT "appointments_client_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP CONSTRAINT "appointments_cancelled_by_fkey"`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP CONSTRAINT "appointments_service_address_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "provider_profiles" DROP CONSTRAINT "provider_profiles_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "favorites" DROP CONSTRAINT "favorites_provider_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "favorites" DROP CONSTRAINT "favorites_client_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "verification_documents" DROP CONSTRAINT "verification_documents_reviewed_by_fkey"`);
        await queryRunner.query(`ALTER TABLE "verification_documents" DROP CONSTRAINT "verification_documents_provider_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "review_images" DROP CONSTRAINT "review_images_review_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "reviews_appointment_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "reviews_provider_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "reviews_client_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "saved_portfolio_images" DROP CONSTRAINT "FK_saved_portfolio_images_image"`);
        await queryRunner.query(`ALTER TABLE "saved_portfolio_images" DROP CONSTRAINT "FK_saved_portfolio_images_user"`);
        await queryRunner.query(`ALTER TABLE "saved_portfolio_images" DROP CONSTRAINT "saved_portfolio_images_image_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "saved_portfolio_images" DROP CONSTRAINT "saved_portfolio_images_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "portfolio_image_likes" DROP CONSTRAINT "FK_portfolio_image_likes_user"`);
        await queryRunner.query(`ALTER TABLE "portfolio_image_likes" DROP CONSTRAINT "FK_portfolio_image_likes_image"`);
        await queryRunner.query(`ALTER TABLE "portfolio_image_likes" DROP CONSTRAINT "portfolio_image_likes_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "portfolio_image_likes" DROP CONSTRAINT "portfolio_image_likes_image_id_fkey"`);
        await queryRunner.query(`DROP INDEX "public"."idx_addresses_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_users_email"`);
        await queryRunner.query(`DROP INDEX "public"."idx_users_phone"`);
        await queryRunner.query(`DROP INDEX "public"."idx_users_user_type"`);
        await queryRunner.query(`DROP INDEX "public"."idx_availability_provider_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_services_provider_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_services_category_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_services_active"`);
        await queryRunner.query(`DROP INDEX "public"."idx_appointment_services_appointment_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_portfolio_provider_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_portfolio_category_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_portfolio_public"`);
        await queryRunner.query(`DROP INDEX "public"."idx_portfolio_images_public_featured"`);
        await queryRunner.query(`DROP INDEX "public"."idx_appointments_client_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_appointments_provider_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_appointments_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_appointments_date"`);
        await queryRunner.query(`DROP INDEX "public"."idx_appointments_number"`);
        await queryRunner.query(`DROP INDEX "public"."idx_appointments_portfolio_image_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_provider_profiles_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_provider_profiles_verified"`);
        await queryRunner.query(`DROP INDEX "public"."idx_favorites_client_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_reviews_provider_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_reviews_rating"`);
        await queryRunner.query(`DROP INDEX "public"."uq_saved_portfolio_images_user_image"`);
        await queryRunner.query(`DROP INDEX "public"."uq_portfolio_image_likes_image_user"`);
        await queryRunner.query(`ALTER TABLE "client_profiles" DROP CONSTRAINT "client_profiles_gender_check"`);
        await queryRunner.query(`ALTER TABLE "client_profiles" DROP CONSTRAINT "client_profiles_hair_type_check"`);
        await queryRunner.query(`ALTER TABLE "client_profiles" DROP CONSTRAINT "client_profiles_hair_length_check"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "users_user_type_check"`);
        await queryRunner.query(`ALTER TABLE "provider_languages" DROP CONSTRAINT "provider_languages_proficiency_check"`);
        await queryRunner.query(`ALTER TABLE "provider_availability" DROP CONSTRAINT "provider_availability_day_of_week_check"`);
        await queryRunner.query(`ALTER TABLE "services" DROP CONSTRAINT "services_price_type_check"`);
        await queryRunner.query(`ALTER TABLE "portfolio_images" DROP CONSTRAINT "portfolio_images_hair_length_check"`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP CONSTRAINT "appointments_status_check"`);
        await queryRunner.query(`ALTER TABLE "provider_profiles" DROP CONSTRAINT "provider_profiles_business_type_check"`);
        await queryRunner.query(`ALTER TABLE "verification_documents" DROP CONSTRAINT "verification_documents_document_type_check"`);
        await queryRunner.query(`ALTER TABLE "verification_documents" DROP CONSTRAINT "verification_documents_status_check"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "reviews_rating_check"`);
        await queryRunner.query(`ALTER TABLE "provider_languages" DROP CONSTRAINT "provider_languages_provider_id_language_code_key"`);
        await queryRunner.query(`ALTER TABLE "favorites" DROP CONSTRAINT "favorites_client_id_provider_id_key"`);
        await queryRunner.query(`ALTER TABLE "saved_portfolio_images" DROP CONSTRAINT "saved_portfolio_images_user_id_image_id_key"`);
        await queryRunner.query(`ALTER TABLE "portfolio_image_likes" DROP CONSTRAINT "portfolio_image_likes_image_id_user_id_key"`);
        await queryRunner.query(`CREATE TABLE "provider_specializations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "specialization" character varying(100) NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "provider_id" uuid, CONSTRAINT "PK_16c0305e0a7f401e739fda1bc1a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_46e1dc9149a94713d4d19646f7" ON "provider_specializations" ("provider_id", "specialization") `);
        await queryRunner.query(`CREATE TABLE "provider_certifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying(255) NOT NULL, "institution" character varying(255) NOT NULL, "year" character varying(4) NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "provider_id" uuid, CONSTRAINT "PK_f088b76647ec12b7ad720d4820c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "provider_languages" DROP COLUMN "provider_id"`);
        await queryRunner.query(`ALTER TABLE "provider_time_off" DROP COLUMN "provider_id"`);
        await queryRunner.query(`ALTER TABLE "services" DROP COLUMN "provider_id"`);
        await queryRunner.query(`ALTER TABLE "services" DROP COLUMN "category_id"`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP COLUMN "cancelled_by"`);
        await queryRunner.query(`ALTER TABLE "favorites" DROP COLUMN "client_id"`);
        await queryRunner.query(`ALTER TABLE "favorites" DROP COLUMN "provider_id"`);
        await queryRunner.query(`ALTER TABLE "verification_documents" DROP COLUMN "provider_id"`);
        await queryRunner.query(`ALTER TABLE "verification_documents" DROP COLUMN "reviewed_by"`);
        await queryRunner.query(`ALTER TABLE "review_images" DROP COLUMN "review_id"`);
        await queryRunner.query(`ALTER TABLE "provider_languages" ADD "providerId" uuid`);
        await queryRunner.query(`ALTER TABLE "provider_time_off" ADD "providerId" uuid`);
        await queryRunner.query(`ALTER TABLE "services" ADD "providerId" uuid`);
        await queryRunner.query(`ALTER TABLE "services" ADD "categoryId" uuid`);
        await queryRunner.query(`ALTER TABLE "provider_profiles" ADD "website" character varying(1024)`);
        await queryRunner.query(`ALTER TABLE "provider_profiles" ADD "instagram" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "provider_profiles" ADD "facebook" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "provider_profiles" ADD "twitter" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "provider_profiles" ADD "youtube" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "provider_profiles" ADD "linkedin" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "favorites" ADD "clientId" uuid`);
        await queryRunner.query(`ALTER TABLE "favorites" ADD "providerId" uuid`);
        await queryRunner.query(`ALTER TABLE "verification_documents" ADD "providerId" uuid`);
        await queryRunner.query(`ALTER TABLE "verification_documents" ADD "reviewedById" uuid`);
        await queryRunner.query(`ALTER TABLE "review_images" ADD "reviewId" uuid`);
        await queryRunner.query(`ALTER TABLE "client_profiles" DROP COLUMN "gender"`);
        await queryRunner.query(`CREATE TYPE "public"."client_profiles_gender_enum" AS ENUM('MALE', 'FEMALE', 'OTHER', 'PREFER_NOT_TO_SAY')`);
        await queryRunner.query(`ALTER TABLE "client_profiles" ADD "gender" "public"."client_profiles_gender_enum"`);
        await queryRunner.query(`ALTER TABLE "client_profiles" DROP COLUMN "hair_type"`);
        await queryRunner.query(`CREATE TYPE "public"."client_profiles_hair_type_enum" AS ENUM('STRAIGHT', 'WAVY', 'CURLY', 'COILY')`);
        await queryRunner.query(`ALTER TABLE "client_profiles" ADD "hair_type" "public"."client_profiles_hair_type_enum"`);
        await queryRunner.query(`ALTER TABLE "client_profiles" DROP COLUMN "hair_length"`);
        await queryRunner.query(`CREATE TYPE "public"."client_profiles_hair_length_enum" AS ENUM('SHORT', 'MEDIUM', 'LONG')`);
        await queryRunner.query(`ALTER TABLE "client_profiles" ADD "hair_length" "public"."client_profiles_hair_length_enum"`);
        await queryRunner.query(`ALTER TABLE "client_profiles" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "client_profiles" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "client_profiles" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "client_profiles" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "client_profiles" ALTER COLUMN "user_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "addresses" ALTER COLUMN "label" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "addresses" ALTER COLUMN "country" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "addresses" ALTER COLUMN "latitude" TYPE numeric(10,6)`);
        await queryRunner.query(`ALTER TABLE "addresses" ALTER COLUMN "longitude" TYPE numeric(10,6)`);
        await queryRunner.query(`ALTER TABLE "addresses" ALTER COLUMN "is_default" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "addresses" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "addresses" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "addresses" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "addresses" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "addresses" ALTER COLUMN "user_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "users_email_key"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "users_phone_key"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "phone"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "phone" character varying(30) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "profile_picture_url"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "profile_picture_url" character varying(1024)`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "user_type"`);
        await queryRunner.query(`CREATE TYPE "public"."users_user_type_enum" AS ENUM('CLIENT', 'PROVIDER', 'BOTH')`);
        await queryRunner.query(`ALTER TABLE "users" ADD "user_type" "public"."users_user_type_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "last_login"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "last_login" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "email_verified" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "phone_verified" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "is_active" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "preferred_language" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "fcm_token"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "fcm_token" character varying(1024)`);
        await queryRunner.query(`ALTER TABLE "provider_locations" ALTER COLUMN "is_primary" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "provider_locations" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "provider_locations" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "provider_locations" ALTER COLUMN "provider_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "provider_locations" ALTER COLUMN "address_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "provider_languages" DROP COLUMN "proficiency"`);
        await queryRunner.query(`CREATE TYPE "public"."provider_languages_proficiency_enum" AS ENUM('BASIC', 'CONVERSATIONAL', 'FLUENT', 'NATIVE')`);
        await queryRunner.query(`ALTER TABLE "provider_languages" ADD "proficiency" "public"."provider_languages_proficiency_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "provider_availability" ALTER COLUMN "is_active" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "provider_availability" ALTER COLUMN "provider_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "provider_time_off" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "provider_time_off" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "service_categories" DROP COLUMN "name_de"`);
        await queryRunner.query(`ALTER TABLE "service_categories" ADD "name_de" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "service_categories" DROP COLUMN "name_en"`);
        await queryRunner.query(`ALTER TABLE "service_categories" ADD "name_en" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "service_categories" DROP CONSTRAINT "service_categories_slug_key"`);
        await queryRunner.query(`ALTER TABLE "service_categories" DROP COLUMN "slug"`);
        await queryRunner.query(`ALTER TABLE "service_categories" ADD "slug" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "service_categories" DROP COLUMN "icon_url"`);
        await queryRunner.query(`ALTER TABLE "service_categories" ADD "icon_url" character varying(1024)`);
        await queryRunner.query(`ALTER TABLE "service_categories" ALTER COLUMN "display_order" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "service_categories" ALTER COLUMN "is_active" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "services" ALTER COLUMN "description" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "services" DROP COLUMN "price_type"`);
        await queryRunner.query(`CREATE TYPE "public"."services_price_type_enum" AS ENUM('FIXED', 'FROM', 'RANGE')`);
        await queryRunner.query(`ALTER TABLE "services" ADD "price_type" "public"."services_price_type_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "services" DROP COLUMN "image_url"`);
        await queryRunner.query(`ALTER TABLE "services" ADD "image_url" character varying(1024)`);
        await queryRunner.query(`ALTER TABLE "services" ALTER COLUMN "is_active" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "services" ALTER COLUMN "display_order" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "services" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "services" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "services" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "services" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "appointment_services" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "appointment_services" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "appointment_services" ALTER COLUMN "appointment_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "appointment_services" ALTER COLUMN "service_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "portfolio_images" DROP COLUMN "image_url"`);
        await queryRunner.query(`ALTER TABLE "portfolio_images" ADD "image_url" character varying(1024) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "portfolio_images" DROP COLUMN "thumbnail_url"`);
        await queryRunner.query(`ALTER TABLE "portfolio_images" ADD "thumbnail_url" character varying(1024)`);
        await queryRunner.query(`ALTER TABLE "portfolio_images" DROP COLUMN "hair_length"`);
        await queryRunner.query(`ALTER TABLE "portfolio_images" ADD "hair_length" "public"."hair_length_enum"`);
        await queryRunner.query(`ALTER TABLE "portfolio_images" ALTER COLUMN "is_featured" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "portfolio_images" ALTER COLUMN "is_public" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "portfolio_images" ALTER COLUMN "view_count" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "portfolio_images" ALTER COLUMN "like_count" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "portfolio_images" ALTER COLUMN "booking_count" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "portfolio_images" ALTER COLUMN "display_order" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "portfolio_images" ALTER COLUMN "display_order" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "portfolio_images" DROP COLUMN "uploaded_at"`);
        await queryRunner.query(`ALTER TABLE "portfolio_images" ADD "uploaded_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "portfolio_images" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "portfolio_images" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "portfolio_images" ALTER COLUMN "provider_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP CONSTRAINT "appointments_appointment_number_key"`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP COLUMN "status"`);
        await queryRunner.query(`CREATE TYPE "public"."appointments_status_enum" AS ENUM('PENDING', 'CONFIRMED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED_BY_CLIENT', 'CANCELLED_BY_PROVIDER', 'NO_SHOW')`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD "status" "public"."appointments_status_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "appointments" ALTER COLUMN "is_mobile_service" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP COLUMN "cancelled_at"`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD "cancelled_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP COLUMN "confirmed_at"`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD "confirmed_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP COLUMN "completed_at"`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD "completed_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "appointments" ALTER COLUMN "client_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "appointments" ALTER COLUMN "provider_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "provider_profiles" DROP COLUMN "business_type"`);
        await queryRunner.query(`CREATE TYPE "public"."provider_profiles_business_type_enum" AS ENUM('INDIVIDUAL', 'SALON', 'BARBER', 'MOBILE')`);
        await queryRunner.query(`ALTER TABLE "provider_profiles" ADD "business_type" "public"."provider_profiles_business_type_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "provider_profiles" ALTER COLUMN "years_of_experience" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "provider_profiles" ALTER COLUMN "years_of_experience" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "provider_profiles" DROP COLUMN "cover_photo_url"`);
        await queryRunner.query(`ALTER TABLE "provider_profiles" ADD "cover_photo_url" character varying(1024)`);
        await queryRunner.query(`ALTER TABLE "provider_profiles" ALTER COLUMN "is_verified" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "provider_profiles" ALTER COLUMN "is_mobile_service" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "provider_profiles" ALTER COLUMN "accepts_same_day_booking" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "provider_profiles" ALTER COLUMN "advance_booking_days" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "provider_profiles" ALTER COLUMN "buffer_time_minutes" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "provider_profiles" ALTER COLUMN "cancellation_policy" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "provider_profiles" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "provider_profiles" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "provider_profiles" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "provider_profiles" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "provider_profiles" DROP COLUMN "verification_submitted_at"`);
        await queryRunner.query(`ALTER TABLE "provider_profiles" ADD "verification_submitted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "provider_profiles" DROP COLUMN "verified_at"`);
        await queryRunner.query(`ALTER TABLE "provider_profiles" ADD "verified_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "provider_profiles" ALTER COLUMN "user_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "favorites" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "favorites" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "verification_documents" DROP COLUMN "document_type"`);
        await queryRunner.query(`CREATE TYPE "public"."verification_documents_document_type_enum" AS ENUM('ID_CARD', 'PASSPORT', 'BUSINESS_LICENSE', 'CERTIFICATE', 'OTHER')`);
        await queryRunner.query(`ALTER TABLE "verification_documents" ADD "document_type" "public"."verification_documents_document_type_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "verification_documents" DROP COLUMN "document_url"`);
        await queryRunner.query(`ALTER TABLE "verification_documents" ADD "document_url" character varying(1024) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "verification_documents" DROP COLUMN "status"`);
        await queryRunner.query(`CREATE TYPE "public"."verification_documents_status_enum" AS ENUM('PENDING', 'APPROVED', 'REJECTED')`);
        await queryRunner.query(`ALTER TABLE "verification_documents" ADD "status" "public"."verification_documents_status_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "verification_documents" DROP COLUMN "uploaded_at"`);
        await queryRunner.query(`ALTER TABLE "verification_documents" ADD "uploaded_at" TIMESTAMP WITH TIME ZONE NOT NULL`);
        await queryRunner.query(`ALTER TABLE "verification_documents" DROP COLUMN "reviewed_at"`);
        await queryRunner.query(`ALTER TABLE "verification_documents" ADD "reviewed_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "review_images" DROP COLUMN "image_url"`);
        await queryRunner.query(`ALTER TABLE "review_images" ADD "image_url" character varying(1024) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "review_images" ALTER COLUMN "display_order" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "review_images" ALTER COLUMN "display_order" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "review_images" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "review_images" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "reviews" ALTER COLUMN "is_anonymous" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP COLUMN "provider_responded_at"`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD "provider_responded_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "reviews" ALTER COLUMN "appointment_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "reviews" ALTER COLUMN "client_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "reviews" ALTER COLUMN "provider_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "saved_portfolio_images" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "saved_portfolio_images" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "saved_portfolio_images" ALTER COLUMN "user_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "saved_portfolio_images" ALTER COLUMN "image_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "portfolio_image_likes" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "portfolio_image_likes" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "portfolio_image_likes" ALTER COLUMN "image_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "portfolio_image_likes" ALTER COLUMN "user_id" DROP NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_d55ec35703b7d805f935a321f0" ON "addresses" ("postal_code") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_97672ac88f789774dd47f7c8be" ON "users" ("email") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_a000cca60bcf04454e72769949" ON "users" ("phone") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_88a33271b3d94a0c4bc14db3b7" ON "service_categories" ("slug") `);
        await queryRunner.query(`CREATE INDEX "IDX_019d74f7abcdcb5a0113010cb0" ON "services" ("name") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_aaee5b216775a0cef6d13f2097" ON "appointments" ("appointment_number") `);
        await queryRunner.query(`ALTER TABLE "favorites" ADD CONSTRAINT "uq_favorites_client_provider" UNIQUE ("clientId", "providerId")`);
        await queryRunner.query(`ALTER TABLE "saved_portfolio_images" ADD CONSTRAINT "uq_saved_portfolio_images_user_image" UNIQUE ("user_id", "image_id")`);
        await queryRunner.query(`ALTER TABLE "portfolio_image_likes" ADD CONSTRAINT "uq_portfolio_image_likes_image_user" UNIQUE ("image_id", "user_id")`);
        await queryRunner.query(`ALTER TABLE "client_profiles" ADD CONSTRAINT "FK_542bfcd136b7ef76af7e4edf1d7" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "addresses" ADD CONSTRAINT "FK_16aac8a9f6f9c1dd6bcb75ec023" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "provider_locations" ADD CONSTRAINT "FK_fde7a51ab97a39a429e3928d33c" FOREIGN KEY ("provider_id") REFERENCES "provider_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "provider_locations" ADD CONSTRAINT "FK_de1bfeeb9f48e8253b4d8d2c519" FOREIGN KEY ("address_id") REFERENCES "addresses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "provider_languages" ADD CONSTRAINT "FK_9ecf7c9e9b03e36782d27a8d0cf" FOREIGN KEY ("providerId") REFERENCES "provider_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "provider_availability" ADD CONSTRAINT "FK_d60be36a0bfa87bd223620fe260" FOREIGN KEY ("provider_id") REFERENCES "provider_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "provider_time_off" ADD CONSTRAINT "FK_6f2a4820ab5d6a7072336a3fa6a" FOREIGN KEY ("providerId") REFERENCES "provider_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "services" ADD CONSTRAINT "FK_8b619ef0a4fe392dbde07eee1e2" FOREIGN KEY ("providerId") REFERENCES "provider_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "services" ADD CONSTRAINT "FK_034b52310c2d211bc979c3cc4e8" FOREIGN KEY ("categoryId") REFERENCES "service_categories"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "appointment_services" ADD CONSTRAINT "FK_923e323e598280a0454e1d1b7cf" FOREIGN KEY ("appointment_id") REFERENCES "appointments"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "appointment_services" ADD CONSTRAINT "FK_5aafcd787c270f1fd2e01376a6b" FOREIGN KEY ("service_id") REFERENCES "services"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "portfolio_images" ADD CONSTRAINT "FK_48fe7ea5d2be8acf7c7a6d81fba" FOREIGN KEY ("provider_id") REFERENCES "provider_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "portfolio_images" ADD CONSTRAINT "FK_1ed2f36b724a6a425882faa61b7" FOREIGN KEY ("style_category_id") REFERENCES "service_categories"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD CONSTRAINT "FK_ccc5bbce58ad6bc96faa428b1e4" FOREIGN KEY ("client_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD CONSTRAINT "FK_e3e268ed1125872144e68b9a41c" FOREIGN KEY ("provider_id") REFERENCES "provider_profiles"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD CONSTRAINT "FK_d6d0348087976c47a7fea2ff807" FOREIGN KEY ("service_address_id") REFERENCES "addresses"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD CONSTRAINT "FK_d9be53f63b17eb304b52906d718" FOREIGN KEY ("portfolio_image_id") REFERENCES "portfolio_images"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "provider_specializations" ADD CONSTRAINT "FK_a2f1fee91b90ff87aa3d7ed58e1" FOREIGN KEY ("provider_id") REFERENCES "provider_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "provider_certifications" ADD CONSTRAINT "FK_9d135e73979c1b6853633a526c4" FOREIGN KEY ("provider_id") REFERENCES "provider_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "provider_profiles" ADD CONSTRAINT "FK_5d1880ed16ff13ea6fd9bca019d" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "favorites" ADD CONSTRAINT "FK_fcf34b36b8c1a74d741fe8452b9" FOREIGN KEY ("clientId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "favorites" ADD CONSTRAINT "FK_f3a1749b54e840d382365ad69bb" FOREIGN KEY ("providerId") REFERENCES "provider_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "verification_documents" ADD CONSTRAINT "FK_aa986e2374d5d97ed3f8fe31a3d" FOREIGN KEY ("providerId") REFERENCES "provider_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "verification_documents" ADD CONSTRAINT "FK_7ff316e64a864f9f0a90e269485" FOREIGN KEY ("reviewedById") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "review_images" ADD CONSTRAINT "FK_3c94c9391ebd2ce1f69b5c4e3ac" FOREIGN KEY ("reviewId") REFERENCES "reviews"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_b0355254b748096d3e4d9a9ac2b" FOREIGN KEY ("appointment_id") REFERENCES "appointments"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_d4e7e923e6bb78a8f0add754493" FOREIGN KEY ("client_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_ba7ceb19946b8b23bf5939c930f" FOREIGN KEY ("provider_id") REFERENCES "provider_profiles"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "saved_portfolio_images" ADD CONSTRAINT "FK_8966b016a782b7d9594d8a23fd5" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "saved_portfolio_images" ADD CONSTRAINT "FK_bef4d3db0b7cc9fb612aa3e755e" FOREIGN KEY ("image_id") REFERENCES "portfolio_images"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "portfolio_image_likes" ADD CONSTRAINT "FK_9839903ccc9d505299a63198a43" FOREIGN KEY ("image_id") REFERENCES "portfolio_images"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "portfolio_image_likes" ADD CONSTRAINT "FK_97e67942f9e1c320c3583a312eb" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "portfolio_image_likes" DROP CONSTRAINT "FK_97e67942f9e1c320c3583a312eb"`);
        await queryRunner.query(`ALTER TABLE "portfolio_image_likes" DROP CONSTRAINT "FK_9839903ccc9d505299a63198a43"`);
        await queryRunner.query(`ALTER TABLE "saved_portfolio_images" DROP CONSTRAINT "FK_bef4d3db0b7cc9fb612aa3e755e"`);
        await queryRunner.query(`ALTER TABLE "saved_portfolio_images" DROP CONSTRAINT "FK_8966b016a782b7d9594d8a23fd5"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_ba7ceb19946b8b23bf5939c930f"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_d4e7e923e6bb78a8f0add754493"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_b0355254b748096d3e4d9a9ac2b"`);
        await queryRunner.query(`ALTER TABLE "review_images" DROP CONSTRAINT "FK_3c94c9391ebd2ce1f69b5c4e3ac"`);
        await queryRunner.query(`ALTER TABLE "verification_documents" DROP CONSTRAINT "FK_7ff316e64a864f9f0a90e269485"`);
        await queryRunner.query(`ALTER TABLE "verification_documents" DROP CONSTRAINT "FK_aa986e2374d5d97ed3f8fe31a3d"`);
        await queryRunner.query(`ALTER TABLE "favorites" DROP CONSTRAINT "FK_f3a1749b54e840d382365ad69bb"`);
        await queryRunner.query(`ALTER TABLE "favorites" DROP CONSTRAINT "FK_fcf34b36b8c1a74d741fe8452b9"`);
        await queryRunner.query(`ALTER TABLE "provider_profiles" DROP CONSTRAINT "FK_5d1880ed16ff13ea6fd9bca019d"`);
        await queryRunner.query(`ALTER TABLE "provider_certifications" DROP CONSTRAINT "FK_9d135e73979c1b6853633a526c4"`);
        await queryRunner.query(`ALTER TABLE "provider_specializations" DROP CONSTRAINT "FK_a2f1fee91b90ff87aa3d7ed58e1"`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP CONSTRAINT "FK_d9be53f63b17eb304b52906d718"`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP CONSTRAINT "FK_d6d0348087976c47a7fea2ff807"`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP CONSTRAINT "FK_e3e268ed1125872144e68b9a41c"`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP CONSTRAINT "FK_ccc5bbce58ad6bc96faa428b1e4"`);
        await queryRunner.query(`ALTER TABLE "portfolio_images" DROP CONSTRAINT "FK_1ed2f36b724a6a425882faa61b7"`);
        await queryRunner.query(`ALTER TABLE "portfolio_images" DROP CONSTRAINT "FK_48fe7ea5d2be8acf7c7a6d81fba"`);
        await queryRunner.query(`ALTER TABLE "appointment_services" DROP CONSTRAINT "FK_5aafcd787c270f1fd2e01376a6b"`);
        await queryRunner.query(`ALTER TABLE "appointment_services" DROP CONSTRAINT "FK_923e323e598280a0454e1d1b7cf"`);
        await queryRunner.query(`ALTER TABLE "services" DROP CONSTRAINT "FK_034b52310c2d211bc979c3cc4e8"`);
        await queryRunner.query(`ALTER TABLE "services" DROP CONSTRAINT "FK_8b619ef0a4fe392dbde07eee1e2"`);
        await queryRunner.query(`ALTER TABLE "provider_time_off" DROP CONSTRAINT "FK_6f2a4820ab5d6a7072336a3fa6a"`);
        await queryRunner.query(`ALTER TABLE "provider_availability" DROP CONSTRAINT "FK_d60be36a0bfa87bd223620fe260"`);
        await queryRunner.query(`ALTER TABLE "provider_languages" DROP CONSTRAINT "FK_9ecf7c9e9b03e36782d27a8d0cf"`);
        await queryRunner.query(`ALTER TABLE "provider_locations" DROP CONSTRAINT "FK_de1bfeeb9f48e8253b4d8d2c519"`);
        await queryRunner.query(`ALTER TABLE "provider_locations" DROP CONSTRAINT "FK_fde7a51ab97a39a429e3928d33c"`);
        await queryRunner.query(`ALTER TABLE "addresses" DROP CONSTRAINT "FK_16aac8a9f6f9c1dd6bcb75ec023"`);
        await queryRunner.query(`ALTER TABLE "client_profiles" DROP CONSTRAINT "FK_542bfcd136b7ef76af7e4edf1d7"`);
        await queryRunner.query(`ALTER TABLE "portfolio_image_likes" DROP CONSTRAINT "uq_portfolio_image_likes_image_user"`);
        await queryRunner.query(`ALTER TABLE "saved_portfolio_images" DROP CONSTRAINT "uq_saved_portfolio_images_user_image"`);
        await queryRunner.query(`ALTER TABLE "favorites" DROP CONSTRAINT "uq_favorites_client_provider"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_aaee5b216775a0cef6d13f2097"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_019d74f7abcdcb5a0113010cb0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_88a33271b3d94a0c4bc14db3b7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a000cca60bcf04454e72769949"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_97672ac88f789774dd47f7c8be"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d55ec35703b7d805f935a321f0"`);
        await queryRunner.query(`ALTER TABLE "portfolio_image_likes" ALTER COLUMN "user_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "portfolio_image_likes" ALTER COLUMN "image_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "portfolio_image_likes" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "portfolio_image_likes" ADD "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "saved_portfolio_images" ALTER COLUMN "image_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "saved_portfolio_images" ALTER COLUMN "user_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "saved_portfolio_images" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "saved_portfolio_images" ADD "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "reviews" ALTER COLUMN "provider_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "reviews" ALTER COLUMN "client_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "reviews" ALTER COLUMN "appointment_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP COLUMN "provider_responded_at"`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD "provider_responded_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "reviews" ALTER COLUMN "is_anonymous" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "review_images" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "review_images" ADD "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "review_images" ALTER COLUMN "display_order" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "review_images" ALTER COLUMN "display_order" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "review_images" DROP COLUMN "image_url"`);
        await queryRunner.query(`ALTER TABLE "review_images" ADD "image_url" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "verification_documents" DROP COLUMN "reviewed_at"`);
        await queryRunner.query(`ALTER TABLE "verification_documents" ADD "reviewed_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "verification_documents" DROP COLUMN "uploaded_at"`);
        await queryRunner.query(`ALTER TABLE "verification_documents" ADD "uploaded_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "verification_documents" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."verification_documents_status_enum"`);
        await queryRunner.query(`ALTER TABLE "verification_documents" ADD "status" character varying(20) DEFAULT 'PENDING'`);
        await queryRunner.query(`ALTER TABLE "verification_documents" DROP COLUMN "document_url"`);
        await queryRunner.query(`ALTER TABLE "verification_documents" ADD "document_url" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "verification_documents" DROP COLUMN "document_type"`);
        await queryRunner.query(`DROP TYPE "public"."verification_documents_document_type_enum"`);
        await queryRunner.query(`ALTER TABLE "verification_documents" ADD "document_type" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "favorites" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "favorites" ADD "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "provider_profiles" ALTER COLUMN "user_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "provider_profiles" DROP COLUMN "verified_at"`);
        await queryRunner.query(`ALTER TABLE "provider_profiles" ADD "verified_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "provider_profiles" DROP COLUMN "verification_submitted_at"`);
        await queryRunner.query(`ALTER TABLE "provider_profiles" ADD "verification_submitted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "provider_profiles" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "provider_profiles" ADD "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "provider_profiles" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "provider_profiles" ADD "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "provider_profiles" ALTER COLUMN "cancellation_policy" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "provider_profiles" ALTER COLUMN "buffer_time_minutes" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "provider_profiles" ALTER COLUMN "advance_booking_days" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "provider_profiles" ALTER COLUMN "accepts_same_day_booking" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "provider_profiles" ALTER COLUMN "is_mobile_service" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "provider_profiles" ALTER COLUMN "is_verified" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "provider_profiles" DROP COLUMN "cover_photo_url"`);
        await queryRunner.query(`ALTER TABLE "provider_profiles" ADD "cover_photo_url" text`);
        await queryRunner.query(`ALTER TABLE "provider_profiles" ALTER COLUMN "years_of_experience" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "provider_profiles" ALTER COLUMN "years_of_experience" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "provider_profiles" DROP COLUMN "business_type"`);
        await queryRunner.query(`DROP TYPE "public"."provider_profiles_business_type_enum"`);
        await queryRunner.query(`ALTER TABLE "provider_profiles" ADD "business_type" character varying(20)`);
        await queryRunner.query(`ALTER TABLE "appointments" ALTER COLUMN "provider_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "appointments" ALTER COLUMN "client_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP COLUMN "completed_at"`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD "completed_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP COLUMN "confirmed_at"`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD "confirmed_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP COLUMN "cancelled_at"`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD "cancelled_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "appointments" ALTER COLUMN "is_mobile_service" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."appointments_status_enum"`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD "status" character varying(30) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD CONSTRAINT "appointments_appointment_number_key" UNIQUE ("appointment_number")`);
        await queryRunner.query(`ALTER TABLE "portfolio_images" ALTER COLUMN "provider_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "portfolio_images" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "portfolio_images" ADD "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "portfolio_images" DROP COLUMN "uploaded_at"`);
        await queryRunner.query(`ALTER TABLE "portfolio_images" ADD "uploaded_at" TIMESTAMP DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "portfolio_images" ALTER COLUMN "display_order" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "portfolio_images" ALTER COLUMN "display_order" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "portfolio_images" ALTER COLUMN "booking_count" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "portfolio_images" ALTER COLUMN "like_count" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "portfolio_images" ALTER COLUMN "view_count" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "portfolio_images" ALTER COLUMN "is_public" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "portfolio_images" ALTER COLUMN "is_featured" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "portfolio_images" DROP COLUMN "hair_length"`);
        await queryRunner.query(`ALTER TABLE "portfolio_images" ADD "hair_length" character varying(20)`);
        await queryRunner.query(`ALTER TABLE "portfolio_images" DROP COLUMN "thumbnail_url"`);
        await queryRunner.query(`ALTER TABLE "portfolio_images" ADD "thumbnail_url" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "portfolio_images" DROP COLUMN "image_url"`);
        await queryRunner.query(`ALTER TABLE "portfolio_images" ADD "image_url" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "appointment_services" ALTER COLUMN "service_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "appointment_services" ALTER COLUMN "appointment_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "appointment_services" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "appointment_services" ADD "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "services" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "services" ADD "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "services" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "services" ADD "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "services" ALTER COLUMN "display_order" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "services" ALTER COLUMN "is_active" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "services" DROP COLUMN "image_url"`);
        await queryRunner.query(`ALTER TABLE "services" ADD "image_url" text`);
        await queryRunner.query(`ALTER TABLE "services" DROP COLUMN "price_type"`);
        await queryRunner.query(`DROP TYPE "public"."services_price_type_enum"`);
        await queryRunner.query(`ALTER TABLE "services" ADD "price_type" character varying(20) DEFAULT 'FIXED'`);
        await queryRunner.query(`ALTER TABLE "services" ALTER COLUMN "description" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "service_categories" ALTER COLUMN "is_active" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "service_categories" ALTER COLUMN "display_order" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "service_categories" DROP COLUMN "icon_url"`);
        await queryRunner.query(`ALTER TABLE "service_categories" ADD "icon_url" text`);
        await queryRunner.query(`ALTER TABLE "service_categories" DROP COLUMN "slug"`);
        await queryRunner.query(`ALTER TABLE "service_categories" ADD "slug" character varying(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "service_categories" ADD CONSTRAINT "service_categories_slug_key" UNIQUE ("slug")`);
        await queryRunner.query(`ALTER TABLE "service_categories" DROP COLUMN "name_en"`);
        await queryRunner.query(`ALTER TABLE "service_categories" ADD "name_en" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "service_categories" DROP COLUMN "name_de"`);
        await queryRunner.query(`ALTER TABLE "service_categories" ADD "name_de" character varying(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "provider_time_off" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "provider_time_off" ADD "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "provider_availability" ALTER COLUMN "provider_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "provider_availability" ALTER COLUMN "is_active" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "provider_languages" DROP COLUMN "proficiency"`);
        await queryRunner.query(`DROP TYPE "public"."provider_languages_proficiency_enum"`);
        await queryRunner.query(`ALTER TABLE "provider_languages" ADD "proficiency" character varying(20)`);
        await queryRunner.query(`ALTER TABLE "provider_locations" ALTER COLUMN "address_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "provider_locations" ALTER COLUMN "provider_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "provider_locations" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "provider_locations" ADD "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "provider_locations" ALTER COLUMN "is_primary" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "fcm_token"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "fcm_token" text`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "preferred_language" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "is_active" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "phone_verified" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "email_verified" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "last_login"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "last_login" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "user_type"`);
        await queryRunner.query(`DROP TYPE "public"."users_user_type_enum"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "user_type" character varying(20) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "profile_picture_url"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "profile_picture_url" text`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "phone"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "phone" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "users_phone_key" UNIQUE ("phone")`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "users_email_key" UNIQUE ("email")`);
        await queryRunner.query(`ALTER TABLE "addresses" ALTER COLUMN "user_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "addresses" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "addresses" ADD "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "addresses" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "addresses" ADD "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "addresses" ALTER COLUMN "is_default" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "addresses" ALTER COLUMN "longitude" TYPE numeric(11,8)`);
        await queryRunner.query(`ALTER TABLE "addresses" ALTER COLUMN "latitude" TYPE numeric(10,8)`);
        await queryRunner.query(`ALTER TABLE "addresses" ALTER COLUMN "country" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "addresses" ALTER COLUMN "label" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "client_profiles" ALTER COLUMN "user_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "client_profiles" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "client_profiles" ADD "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "client_profiles" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "client_profiles" ADD "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "client_profiles" DROP COLUMN "hair_length"`);
        await queryRunner.query(`DROP TYPE "public"."client_profiles_hair_length_enum"`);
        await queryRunner.query(`ALTER TABLE "client_profiles" ADD "hair_length" character varying(20)`);
        await queryRunner.query(`ALTER TABLE "client_profiles" DROP COLUMN "hair_type"`);
        await queryRunner.query(`DROP TYPE "public"."client_profiles_hair_type_enum"`);
        await queryRunner.query(`ALTER TABLE "client_profiles" ADD "hair_type" character varying(20)`);
        await queryRunner.query(`ALTER TABLE "client_profiles" DROP COLUMN "gender"`);
        await queryRunner.query(`DROP TYPE "public"."client_profiles_gender_enum"`);
        await queryRunner.query(`ALTER TABLE "client_profiles" ADD "gender" character varying(20)`);
        await queryRunner.query(`ALTER TABLE "review_images" DROP COLUMN "reviewId"`);
        await queryRunner.query(`ALTER TABLE "verification_documents" DROP COLUMN "reviewedById"`);
        await queryRunner.query(`ALTER TABLE "verification_documents" DROP COLUMN "providerId"`);
        await queryRunner.query(`ALTER TABLE "favorites" DROP COLUMN "providerId"`);
        await queryRunner.query(`ALTER TABLE "favorites" DROP COLUMN "clientId"`);
        await queryRunner.query(`ALTER TABLE "provider_profiles" DROP COLUMN "linkedin"`);
        await queryRunner.query(`ALTER TABLE "provider_profiles" DROP COLUMN "youtube"`);
        await queryRunner.query(`ALTER TABLE "provider_profiles" DROP COLUMN "twitter"`);
        await queryRunner.query(`ALTER TABLE "provider_profiles" DROP COLUMN "facebook"`);
        await queryRunner.query(`ALTER TABLE "provider_profiles" DROP COLUMN "instagram"`);
        await queryRunner.query(`ALTER TABLE "provider_profiles" DROP COLUMN "website"`);
        await queryRunner.query(`ALTER TABLE "services" DROP COLUMN "categoryId"`);
        await queryRunner.query(`ALTER TABLE "services" DROP COLUMN "providerId"`);
        await queryRunner.query(`ALTER TABLE "provider_time_off" DROP COLUMN "providerId"`);
        await queryRunner.query(`ALTER TABLE "provider_languages" DROP COLUMN "providerId"`);
        await queryRunner.query(`ALTER TABLE "review_images" ADD "review_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "verification_documents" ADD "reviewed_by" uuid`);
        await queryRunner.query(`ALTER TABLE "verification_documents" ADD "provider_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "favorites" ADD "provider_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "favorites" ADD "client_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD "cancelled_by" uuid`);
        await queryRunner.query(`ALTER TABLE "services" ADD "category_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "services" ADD "provider_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "provider_time_off" ADD "provider_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "provider_languages" ADD "provider_id" uuid NOT NULL`);
        await queryRunner.query(`DROP TABLE "provider_certifications"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_46e1dc9149a94713d4d19646f7"`);
        await queryRunner.query(`DROP TABLE "provider_specializations"`);
        await queryRunner.query(`ALTER TABLE "portfolio_image_likes" ADD CONSTRAINT "portfolio_image_likes_image_id_user_id_key" UNIQUE ("image_id", "user_id")`);
        await queryRunner.query(`ALTER TABLE "saved_portfolio_images" ADD CONSTRAINT "saved_portfolio_images_user_id_image_id_key" UNIQUE ("user_id", "image_id")`);
        await queryRunner.query(`ALTER TABLE "favorites" ADD CONSTRAINT "favorites_client_id_provider_id_key" UNIQUE ("client_id", "provider_id")`);
        await queryRunner.query(`ALTER TABLE "provider_languages" ADD CONSTRAINT "provider_languages_provider_id_language_code_key" UNIQUE ("provider_id", "language_code")`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "reviews_rating_check" CHECK (((rating >= 1) AND (rating <= 5)))`);
        await queryRunner.query(`ALTER TABLE "verification_documents" ADD CONSTRAINT "verification_documents_status_check" CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "verification_documents" ADD CONSTRAINT "verification_documents_document_type_check" CHECK (((document_type)::text = ANY ((ARRAY['ID_CARD'::character varying, 'PASSPORT'::character varying, 'BUSINESS_LICENSE'::character varying, 'CERTIFICATE'::character varying, 'OTHER'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "provider_profiles" ADD CONSTRAINT "provider_profiles_business_type_check" CHECK (((business_type)::text = ANY ((ARRAY['INDIVIDUAL'::character varying, 'SALON'::character varying, 'BARBER'::character varying, 'MOBILE'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD CONSTRAINT "appointments_status_check" CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'CONFIRMED'::character varying, 'IN_PROGRESS'::character varying, 'COMPLETED'::character varying, 'CANCELLED_BY_CLIENT'::character varying, 'CANCELLED_BY_PROVIDER'::character varying, 'NO_SHOW'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "portfolio_images" ADD CONSTRAINT "portfolio_images_hair_length_check" CHECK (((hair_length)::text = ANY ((ARRAY['SHORT'::character varying, 'MEDIUM'::character varying, 'LONG'::character varying, 'EXTRA_LONG'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "services" ADD CONSTRAINT "services_price_type_check" CHECK (((price_type)::text = ANY ((ARRAY['FIXED'::character varying, 'FROM'::character varying, 'RANGE'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "provider_availability" ADD CONSTRAINT "provider_availability_day_of_week_check" CHECK (((day_of_week >= 0) AND (day_of_week <= 6)))`);
        await queryRunner.query(`ALTER TABLE "provider_languages" ADD CONSTRAINT "provider_languages_proficiency_check" CHECK (((proficiency)::text = ANY ((ARRAY['BASIC'::character varying, 'CONVERSATIONAL'::character varying, 'FLUENT'::character varying, 'NATIVE'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "users_user_type_check" CHECK (((user_type)::text = ANY ((ARRAY['CLIENT'::character varying, 'PROVIDER'::character varying, 'BOTH'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "client_profiles" ADD CONSTRAINT "client_profiles_hair_length_check" CHECK (((hair_length)::text = ANY ((ARRAY['SHORT'::character varying, 'MEDIUM'::character varying, 'LONG'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "client_profiles" ADD CONSTRAINT "client_profiles_hair_type_check" CHECK (((hair_type)::text = ANY ((ARRAY['STRAIGHT'::character varying, 'WAVY'::character varying, 'CURLY'::character varying, 'COILY'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "client_profiles" ADD CONSTRAINT "client_profiles_gender_check" CHECK (((gender)::text = ANY ((ARRAY['MALE'::character varying, 'FEMALE'::character varying, 'OTHER'::character varying, 'PREFER_NOT_TO_SAY'::character varying])::text[])))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_portfolio_image_likes_image_user" ON "portfolio_image_likes" ("image_id", "user_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_saved_portfolio_images_user_image" ON "saved_portfolio_images" ("image_id", "user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_reviews_rating" ON "reviews" ("rating") `);
        await queryRunner.query(`CREATE INDEX "idx_reviews_provider_id" ON "reviews" ("provider_id") `);
        await queryRunner.query(`CREATE INDEX "idx_favorites_client_id" ON "favorites" ("client_id") `);
        await queryRunner.query(`CREATE INDEX "idx_provider_profiles_verified" ON "provider_profiles" ("is_verified") `);
        await queryRunner.query(`CREATE INDEX "idx_provider_profiles_user_id" ON "provider_profiles" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_appointments_portfolio_image_id" ON "appointments" ("portfolio_image_id") `);
        await queryRunner.query(`CREATE INDEX "idx_appointments_number" ON "appointments" ("appointment_number") `);
        await queryRunner.query(`CREATE INDEX "idx_appointments_date" ON "appointments" ("appointment_date") `);
        await queryRunner.query(`CREATE INDEX "idx_appointments_status" ON "appointments" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_appointments_provider_id" ON "appointments" ("provider_id") `);
        await queryRunner.query(`CREATE INDEX "idx_appointments_client_id" ON "appointments" ("client_id") `);
        await queryRunner.query(`CREATE INDEX "idx_portfolio_images_public_featured" ON "portfolio_images" ("is_featured", "is_public") `);
        await queryRunner.query(`CREATE INDEX "idx_portfolio_public" ON "portfolio_images" ("is_public") `);
        await queryRunner.query(`CREATE INDEX "idx_portfolio_category_id" ON "portfolio_images" ("style_category_id") `);
        await queryRunner.query(`CREATE INDEX "idx_portfolio_provider_id" ON "portfolio_images" ("provider_id") `);
        await queryRunner.query(`CREATE INDEX "idx_appointment_services_appointment_id" ON "appointment_services" ("appointment_id") `);
        await queryRunner.query(`CREATE INDEX "idx_services_active" ON "services" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "idx_services_category_id" ON "services" ("category_id") `);
        await queryRunner.query(`CREATE INDEX "idx_services_provider_id" ON "services" ("provider_id") `);
        await queryRunner.query(`CREATE INDEX "idx_availability_provider_id" ON "provider_availability" ("provider_id") `);
        await queryRunner.query(`CREATE INDEX "idx_users_user_type" ON "users" ("user_type") `);
        await queryRunner.query(`CREATE INDEX "idx_users_phone" ON "users" ("phone") `);
        await queryRunner.query(`CREATE INDEX "idx_users_email" ON "users" ("email") `);
        await queryRunner.query(`CREATE INDEX "idx_addresses_user_id" ON "addresses" ("user_id") `);
        await queryRunner.query(`ALTER TABLE "portfolio_image_likes" ADD CONSTRAINT "portfolio_image_likes_image_id_fkey" FOREIGN KEY ("image_id") REFERENCES "portfolio_images"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "portfolio_image_likes" ADD CONSTRAINT "portfolio_image_likes_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "portfolio_image_likes" ADD CONSTRAINT "FK_portfolio_image_likes_image" FOREIGN KEY ("image_id") REFERENCES "portfolio_images"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "portfolio_image_likes" ADD CONSTRAINT "FK_portfolio_image_likes_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "saved_portfolio_images" ADD CONSTRAINT "saved_portfolio_images_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "saved_portfolio_images" ADD CONSTRAINT "saved_portfolio_images_image_id_fkey" FOREIGN KEY ("image_id") REFERENCES "portfolio_images"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "saved_portfolio_images" ADD CONSTRAINT "FK_saved_portfolio_images_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "saved_portfolio_images" ADD CONSTRAINT "FK_saved_portfolio_images_image" FOREIGN KEY ("image_id") REFERENCES "portfolio_images"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "reviews_client_id_fkey" FOREIGN KEY ("client_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "reviews_provider_id_fkey" FOREIGN KEY ("provider_id") REFERENCES "provider_profiles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "reviews_appointment_id_fkey" FOREIGN KEY ("appointment_id") REFERENCES "appointments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "review_images" ADD CONSTRAINT "review_images_review_id_fkey" FOREIGN KEY ("review_id") REFERENCES "reviews"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "verification_documents" ADD CONSTRAINT "verification_documents_provider_id_fkey" FOREIGN KEY ("provider_id") REFERENCES "provider_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "verification_documents" ADD CONSTRAINT "verification_documents_reviewed_by_fkey" FOREIGN KEY ("reviewed_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "favorites" ADD CONSTRAINT "favorites_client_id_fkey" FOREIGN KEY ("client_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "favorites" ADD CONSTRAINT "favorites_provider_id_fkey" FOREIGN KEY ("provider_id") REFERENCES "provider_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "provider_profiles" ADD CONSTRAINT "provider_profiles_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD CONSTRAINT "appointments_service_address_id_fkey" FOREIGN KEY ("service_address_id") REFERENCES "addresses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD CONSTRAINT "appointments_cancelled_by_fkey" FOREIGN KEY ("cancelled_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD CONSTRAINT "appointments_client_id_fkey" FOREIGN KEY ("client_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD CONSTRAINT "appointments_provider_id_fkey" FOREIGN KEY ("provider_id") REFERENCES "provider_profiles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD CONSTRAINT "fk_appointments_portfolio_image" FOREIGN KEY ("portfolio_image_id") REFERENCES "portfolio_images"("id") ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "portfolio_images" ADD CONSTRAINT "portfolio_images_provider_id_fkey" FOREIGN KEY ("provider_id") REFERENCES "provider_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "portfolio_images" ADD CONSTRAINT "portfolio_images_style_category_id_fkey" FOREIGN KEY ("style_category_id") REFERENCES "service_categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "portfolio_images" ADD CONSTRAINT "FK_portfolio_images_style_category" FOREIGN KEY ("style_category_id") REFERENCES "service_categories"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "appointment_services" ADD CONSTRAINT "appointment_services_appointment_id_fkey" FOREIGN KEY ("appointment_id") REFERENCES "appointments"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "appointment_services" ADD CONSTRAINT "appointment_services_service_id_fkey" FOREIGN KEY ("service_id") REFERENCES "services"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "services" ADD CONSTRAINT "services_provider_id_fkey" FOREIGN KEY ("provider_id") REFERENCES "provider_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "services" ADD CONSTRAINT "services_category_id_fkey" FOREIGN KEY ("category_id") REFERENCES "service_categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "provider_time_off" ADD CONSTRAINT "provider_time_off_provider_id_fkey" FOREIGN KEY ("provider_id") REFERENCES "provider_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "provider_availability" ADD CONSTRAINT "provider_availability_provider_id_fkey" FOREIGN KEY ("provider_id") REFERENCES "provider_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "provider_languages" ADD CONSTRAINT "provider_languages_provider_id_fkey" FOREIGN KEY ("provider_id") REFERENCES "provider_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "provider_locations" ADD CONSTRAINT "provider_locations_provider_id_fkey" FOREIGN KEY ("provider_id") REFERENCES "provider_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "provider_locations" ADD CONSTRAINT "provider_locations_address_id_fkey" FOREIGN KEY ("address_id") REFERENCES "addresses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "addresses" ADD CONSTRAINT "addresses_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "client_profiles" ADD CONSTRAINT "client_profiles_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
